# name: re.error 
exception re.error(msg, pattern=None, pos=None)