# name: c.PyErr_SetInterrupt 
void PyErr_SetInterrupt()