# name: c.PyErr_NormalizeExc 
void PyErr_NormalizeException(PyObject**exc, PyObject**val, PyObject**tb)