# name: try:
    res = await 
try:
    res = await shield(something())
except CancelledError:
    res = None